### ISSUE TITLE
About the usage of initial hidden state in calculating attention

### ISSUE THREAD

**Issue by leitro** [keon/seq2seq#1]
Hi, it is a super good implementation for seq2seq in pytorch, but I have a doubt in the following line:

https://github.com/keon/seq2seq/blob/26ed9b46ed667c5b3df573eb7d36901fb7c28121/model.py#L101

We can see from the code here, the hidden state (which is to calculate the attention) is the final hidden state from encoder, while in theory it should be the hidden state from decoder at current time step. Do you agree? Thx:-)

**Comment by bentrevett** [comment]
That is just the initial hidden state for the decoder, which is the final hidden state from the encoder. So you can say that's at time-step t0.

It gets all subsequent hidden states from the output of the decoder at time step t.

**Comment by leitro** [comment]
Yep, you are right, and there are different ways to initialize the first hidden state of decoder, either the last hidden state of encoder or all zeros. I tried both, and the performance are more or less the same. It's time to close it. Cheers!
