### ISSUE TITLE
[EROOR] Not Work Relu

### ISSUE THREAD

**Issue by kenya-sk** [keon/seq2seq#20]
The following error occurs when executing "train.py".
```
TypeError: relu() got an unexpected keyword argument 'dim'
```

I checked the official documentation of pyTorch and it was not necessary to specify "dim" in any version.

**Comment by WendongGan** [comment]
Have this problem been solved? I also meet the problem.

**Comment by kenya-sk** [comment]
> Have this problem been solved? I also meet the problem.

@UESTCgan
I do not know because there was no reply, but maybe it has not been resolved.
There are some that I implemented and confirmed the operation. Please refer to it if you like.
https://github.com/kenya-sk/seq2seq_pytorch
