### ISSUE TITLE
Use of non-linearity in calculating attention

### ISSUE THREAD

**Issue by tarun005** [keon/seq2seq#3]
Are you sure there is no tanh/relu in line 47 of  seq2seq/model.py? If I understand it correctly, this is a one-layer NN, so shouldn't there be a non-linearity in between?

**Comment by ruizheliUOA** [comment]
@tarun005 Yes, you are right. This problem is also mentioned in [here](https://github.com/AuCson/PyTorch-Batch-Attention-Seq2seq/issues/3). You can find the solution in that link.
