### ISSUE TITLE
what is the nn.Parameter  v for?

### ISSUE THREAD

**Issue by liuyijiang1994** [keon/seq2seq#7]

**Comment by liuyijiang1994** [comment]
hi, I find that in your code there is a parameter v in the model Attention , I wonder what this is for, thanks!

**Comment by pskrunner14** [comment]
@liuyijiang1994 I think `v` is essentially the applied attention weights that assign a score to attention energies to help the decoder understand the context and output the most relevant information/tokens.

You might want to give [this](https://arxiv.org/abs/1508.04025) paper a read, it explains attention for seq2seq autoencoders quite well :)

**Comment by liuyijiang1994** [comment]
> @liuyijiang1994 I think `v` is essentially the applied attention weights that assign a score to attention energies to help the decoder understand the context and output the most relevant information/tokens.
> 
> You might want to give [this](https://arxiv.org/abs/1508.04025) paper a read, it explains attention for seq2seq autoencoders quite well :)

much thanks!
