### ISSUE TITLE
Model still uses teacher forcing when evaluating

### ISSUE THREAD

**Issue by ruizheliUOA** [keon/seq2seq#8]
Hi, I think there might be a bug in evaluate function from train.py; when the trained model is evaluated using the evaluate function, the 'model' still uses teacher forcing to evaluate the trained model. Therefore, there might be 50% probability to use true labels as an input for the hidden state at the next timestamp. I think this operation might be unsuitable. Because I think we always need to use the predicted labels as an input for the next hidden state to evaluate.

**Comment by pskrunner14** [comment]
@ruizheliUOA yes you're right, there needs to be an `is_eval` flag that tells the `seq2seq` model not to use teacher forcing when evaluating.
